# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tfstate-471448382412-us-east-1"
    dynamodb_table = "terraform-locks-471448382412"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "us-east-1"
  }
}
